name: Bug Report
description: File a bug report to help us improve Crypthold
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Crypthold Version
      description: What version of Crypthold are you using? (Check package.json or npm list)
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS version, Node.js version, hardware (if relevant).
      placeholder: |
        Node.js v22.0.0
        Windows 11
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., stack traces, screenshots).
